'use strict';const M=ProbeModel,V=ProbeView;let state=M.initial(),completed=2;state.level=3;const $=id=>document.getElementById(id);
function tab(name){$('routeSection').classList.toggle('active',name==='route');$('gameSection').classList.toggle('active',name==='game');document.querySelectorAll('[data-tab]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.tab===name));}
function render(){ $('route').innerHTML=V.menu(completed);$('game').innerHTML=V.game(state);$('status').textContent=state.message; }
function sheet(title,text,collection=false){$('sheetTitle').textContent=title;$('sheetText').textContent=text;$('collected').hidden=!collection;$('collected').innerHTML=Array.from({length:completed},(_,i)=>'<span>'+String(i+1).padStart(2,'0')+'</span>').join('');$('sheet').showModal();}
function complete(){if(M.used(state).size===18){completed=Math.max(completed,state.level);sheet('Das passt!','Ein kleines Stück geschafft. Deine nächste Station wartet auf der Reise.');render();}}
function activate(target){const level=target.closest('[data-level]'),piece=target.closest('[data-piece]'),cell=target.closest('[data-cell]'),action=target.closest('[data-action]');if(level){const n=+level.dataset.level;if(n>completed+1){state.message='Diese Station öffnet sich nach dem nächsten Rätsel.';render();return;}state=M.initial();state.level=n;tab('game');render();return;}
if(action){const a=action.dataset.action;if(a==='route'){tab('route');return;}if(a==='collection'){sheet('Deine Lichtstücke','So wächst deine Sammlung mit jedem gelösten Rätsel. Die Stationen dieser Stilprobe sind Beispiele.',true);return;}if(a==='settings'){sheet('In deinem Tempo','Antippe ein Teil und danach sein Ansatzfeld. Der weiße Punkt zeigt den Ansatz. Diese Probe konzentriert sich auf Gestaltung und Antippen; Ziehen und persönliche Einstellungen bleiben in der bestehenden App.');return;}if(a==='undo')M.undo(state);if(a==='hint')M.hint(state);if(a==='reset'){const n=state.level;state=M.initial();state.level=n;}render();complete();return;}
if(piece){state.selected=state.selected===+piece.dataset.piece?null:+piece.dataset.piece;state.message=state.selected===null?'Teil abgewählt.':'Wähle das Ansatzfeld für den weißen Punkt.';render();return;}
if(cell){const at=cell.dataset.cell.split(',').map(Number);if(state.selected!==null)M.place(state,state.selected,at);else{const id=M.used(state).get(at.join(','));if(id!==undefined)M.take(state,id);}render();complete();}}
for(const id of ['route','game']){$(id).addEventListener('click',e=>activate(e.target));$(id).addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();activate(e.target);}});}
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>tab(b.dataset.tab));document.querySelector('.tools').addEventListener('click',e=>{const b=e.target.closest('[data-test]');if(!b)return;if(b.dataset.test==='reset'){state=M.initial();state.level=3;completed=2;}else M.automatic(state,b.dataset.test);render();if(b.dataset.test==='full')complete();});$('closeSheet').onclick=()=>{$('sheet').close();if(M.used(state).size===18)tab('route');};render();
