const fs=require('fs'),vm=require('vm'),assert=require('assert/strict');
const html=fs.readFileSync(__dirname+'/index.html','utf8'),elements={};
function element(){const classes=new Set();return {setAttribute(k,v){this[k]=v;},style:{},checked:false,classList:{add:n=>classes.add(n),remove:n=>classes.delete(n),toggle:(n,on)=>on?classes.add(n):classes.delete(n)},addEventListener(){},showModal(){this.open=true;},close(){this.open=false;},innerHTML:'',textContent:''};}
for(const m of html.matchAll(/id="([^"]+)"/g))elements[m[1]]=element();
const brand=element(),store=new Map([['lumahex-journey-v4',JSON.stringify({done:[0,2],index:3,introSeen:true,sound:false,attempts:{3:{placements:{0:[0,0]}}}})]]);
const ctx={HexCurriculum:require('./curriculum.js'),HexFinish:require('./finish.js'),HexSave:require('./save.js'),HexEngine:require('./engine.js'),HexMotifs:require('./motifs.js'),localStorage:{getItem:k=>store.get(k)||null,setItem:(k,v)=>store.set(k,v)},document:{addEventListener(){},getElementById:id=>{assert.ok(elements[id],'known DOM element '+id);return elements[id];},querySelector:s=>s==='.brand'?brand:null,querySelectorAll:()=>Object.values(elements).filter(e=>e.open)},window:{},navigator:{},location:{protocol:'file:'},setTimeout:()=>1,clearTimeout(){}};
vm.createContext(ctx);const run=s=>vm.runInContext(s,ctx);run(fs.readFileSync(__dirname+'/game.js','utf8'));

assert.equal(elements.levelNumber.textContent,'01','new journey follows curriculum rather than catalog ID');assert.deepEqual(JSON.parse(store.get('lumahex-journey-v5')).done,[0,2],'old collection survives reordered journey');assert.equal(elements.home.open,true);elements.homeContinue.onclick();
elements.gameJourney.onclick();assert.ok(!html.includes('journeyChapterSelect'));assert.equal(elements.journeyNext.disabled,false,'old completed chapters remain reachable');assert.equal((elements.journeyChapters.innerHTML.match(/data-journey=/g)||[]).length,10);assert.ok(elements.journeyChapters.innerHTML.includes('current'));assert.equal(run('tutorialProgress'),6,'existing players are not forced through introduction');
const C=ctx.HexCurriculum,order=C.order;
elements.journeyChapters.onclick({target:{closest:()=>({dataset:{journey:String(order[299])}})}});assert.equal(elements.levelNumber.textContent,'01','locked target cannot be opened');
elements.journeyContinue.onclick();elements.testAlmost.onclick();assert.equal(run('data.pieces.length-Object.keys(placements).length'),1);elements.testStep.onclick();assert.equal(run('done.has(ORDER[0])'),true);elements.next.onclick();assert.equal(elements.levelNumber.textContent,'02');
run('attempts={};done=new Set(ORDER.slice(0,9));load(ORDER[8])');elements.gameJourney.onclick();assert.equal(elements.journeyNext.disabled,true);elements.journeyContinue.onclick();assert.equal(elements.levelNumber.textContent,'10');elements.testFull.onclick();elements.next.onclick();assert.equal(elements.levelNumber.textContent,'11');elements.gameJourney.onclick();assert.equal(run('journeyChapter'),1);elements.journeyPrevious.onclick();assert.equal(run('journeyChapter'),0);elements.journeyNext.onclick();assert.equal(run('journeyChapter'),1);
run('attempts={};done=new Set([0,50]);load(60)');elements.testAlmost.onclick();const partial=run('JSON.stringify(placements)');elements.gameJourney.onclick();assert.equal(run('accessible(50)'),true);assert.equal(run('accessible(60)'),true);assert.equal(run('chapterAccessible(chapterOf(60))'),true);
run('load(60)');assert.equal(run('JSON.stringify(placements)'),partial);elements.collection.onclick();assert.equal((elements.galleryGrid.innerHTML.match(/data-motif=/g)||[]).length,run('done.size'));
for(const route of ['menu','gallery','journey','home']){run('routeView('+JSON.stringify(route)+')');assert.equal(Object.values(elements).filter(e=>e.open).length,1);}
run("routeView('menu')");elements.openHelp.onclick();ctx.window.LumaBack();assert.equal(elements.menu.open,true);elements.openBackup.onclick();const backup=elements.backupCode.value;elements.backupCode.value='broken';elements.checkBackup.onclick();assert.equal(elements.confirmRestore.hidden,true);elements.backupCode.value=backup;elements.checkBackup.onclick();assert.equal(elements.confirmRestore.hidden,false);let reloaded=false;ctx.location.reload=()=>reloaded=true;elements.confirmRestore.onclick();assert.equal(reloaded,true);ctx.window.LumaBack();assert.equal(elements.menu.open,true);ctx.window.LumaBack();assert.equal(elements.home.open,true);assert.equal(ctx.window.LumaBack(),false);
run('closeDialogs();load(60)');const before=run('JSON.stringify(placements)');elements.reset.onclick();assert.equal(elements.resetDialog.open,true);elements.cancelReset.onclick();assert.equal(run('JSON.stringify(placements)'),before);elements.reset.onclick();elements.confirmReset.onclick();assert.equal(run('Object.keys(placements).length'),0);elements.undo.onclick();assert.equal(run('JSON.stringify(placements)'),before);
run("routeView('menu')");elements.jumpNumber.value=1200;elements.jumpLevel.onclick();assert.equal(elements.levelNumber.textContent,'1200');run('done=new Set(ORDER)');elements.testFull.onclick();elements.next.onclick();assert.equal(elements.journey.open,true);elements.replay.onclick();assert.equal(run('Object.keys(placements).length'),0);
console.log('PASS: curriculum navigation, locked chapters, legacy IDs/partial progress, backup, reset, Android back, test jumps and completed journey.');
// Brand-new player: six separate lessons, persisted progress, repeat and skip.
for(const e of Object.values(elements))e.close();store.clear();const fresh={...ctx,window:{}};vm.createContext(fresh);const learn=s=>vm.runInContext(s,fresh);learn(fs.readFileSync(__dirname+'/game.js','utf8'));assert.equal(elements.intro.open,true);elements.start.onclick();assert.equal(learn('tutorialIndex'),0);assert.equal(learn('data.pieces.length'),1);elements.collection.onclick();elements.galleryContinue.onclick();assert.equal(learn('tutorialIndex'),0,'return to unfinished practice does not skip a lesson');const savedAttempts=JSON.stringify(JSON.parse(store.get('lumahex-journey-v5')).attempts);
for(let n=0;n<6;n++){assert.equal(learn('tutorialIndex'),n);assert.equal(elements.lessonGuide.hidden,false);elements.testFull.onclick();assert.equal(learn('tutorialProgress'),n+1);assert.equal(learn('done.size'),0,'lesson does not unlock collection');assert.equal(JSON.stringify(JSON.parse(store.get('lumahex-journey-v5')).attempts),savedAttempts,'lesson does not replace regular pieces');elements.next.onclick();}
assert.equal(elements.home.open,true);assert.equal(learn('tutorialIndex'),null);assert.equal(JSON.parse(store.get('lumahex-journey-v5')).tutorialProgress,6);elements.homeContinue.onclick();assert.equal(elements.lessonGuide.hidden,true);assert.equal(elements.levelNumber.textContent,'01');
elements.gameJourney.onclick();elements.openCourse.onclick();assert.equal(learn('tutorialIndex'),0,'completed course can be replayed');elements.gameHome.onclick();assert.equal(learn('tutorialIndex'),null,'home exits practice safely');elements.homeContinue.onclick();assert.equal(elements.lessonGuide.hidden,true);elements.openCourse.onclick();elements.skipLesson.onclick();assert.equal(learn('tutorialIndex'),null);
learn('tutorialProgress=2;persist()');for(const e of Object.values(elements))e.close();const resumed={...ctx,window:{}};vm.createContext(resumed);vm.runInContext(fs.readFileSync(__dirname+'/game.js','utf8'),resumed);elements.homeContinue.onclick();assert.equal(vm.runInContext('tutorialIndex',resumed),2,'unfinished course resumes at next lesson');
console.log('PASS: six playable lessons, course resume/replay/skip, introduction migration and isolation from regular progress.');

// Only adjacent solved stations light their connecting path, without repeated visible labels.
run('attempts={};done=new Set(ORDER.slice(0,2))');let pathHTML=run('pathMarkup(ORDER.slice(0,10))');assert.equal((pathHTML.match(/class="completed-route"/g)||[]).length,1);assert.equal((pathHTML.match(/<text /g)||[]).length,10);assert.ok(!/<(?:b|span|small)>/.test(pathHTML),'station labels appear only inside hexagons');run('done=new Set([ORDER[0],ORDER[2]])');assert.equal((run('pathMarkup(ORDER.slice(0,10))').match(/class="completed-route"/g)||[]).length,0,'unfinished gap does not light up');run('done=new Set(ORDER.slice(0,10))');assert.equal((run('pathMarkup(ORDER.slice(0,10))').match(/class="completed-route"/g)||[]).length,9);console.log('PASS: completed path segments, unfinished gaps and one visible number per station.');
run('tutorialIndex=null;done=new Set();load(ORDER[0]);testAction("full")');
assert.equal(elements.winTitle.textContent,'Geschafft!');assert.ok(elements.winQuote.textContent.length>10);assert.equal(elements.winText.textContent,'');
const firstText=elements.winQuote.textContent;run('complete(false)');assert.equal(elements.winQuote.textContent,firstText);
run('done=new Set(ORDER.slice(0,9));load(ORDER[9]);testAction("full")');assert.equal(elements.winTitle.textContent,'Etappe geschafft!');assert.equal(elements.winEyebrow.textContent,'TESTLAUF');assert.ok(elements.winText.textContent.includes('zehn'));assert.ok(JSON.parse(store.get('lumahex-journey-v5')).finishMemory);
console.log('PASS: normal completion, stable text, milestone completion and persisted text history.');
