const fs=require('fs'),vm=require('vm'),assert=require('assert/strict');
const html=fs.readFileSync(__dirname+'/index.html','utf8'),elements={};
function element(){const classes=new Set();return {setAttribute(k,v){this[k]=v;},style:{},checked:false,classList:{add:n=>classes.add(n),remove:n=>classes.delete(n),toggle:(n,on)=>on?classes.add(n):classes.delete(n)},addEventListener(){},showModal(){this.open=true;},close(){this.open=false;},innerHTML:'',textContent:''};}
for(const m of html.matchAll(/id="([^"]+)"/g))elements[m[1]]=element();
const brand=element(),store=new Map([['lumahex-journey-v4',JSON.stringify({done:[0,2],index:3,introSeen:true,sound:false,attempts:{3:{placements:{0:[0,0]}}}})]]);
const ctx={HexSave:require('./save.js'),HexEngine:require('./engine.js'),HexMotifs:require('./motifs.js'),localStorage:{getItem:k=>store.get(k)||null,setItem:(k,v)=>store.set(k,v)},document:{addEventListener(){},getElementById:id=>{assert.ok(elements[id],'known DOM element '+id);return elements[id];},querySelector:s=>s==='.brand'?brand:null,querySelectorAll:()=>Object.values(elements).filter(e=>e.open)},window:{},navigator:{},location:{protocol:'file:'},setTimeout:()=>1,clearTimeout(){}};
vm.createContext(ctx);const run=s=>vm.runInContext(s,ctx);run(fs.readFileSync(__dirname+'/game.js','utf8'));
assert.equal(elements.levelNumber.textContent,'02','restart fills earliest open gap');assert.deepEqual(JSON.parse(store.get('lumahex-journey-v5')).done,[0,2]);assert.equal(elements.home.open,true);elements.homeContinue.onclick();
elements.gameJourney.onclick();assert.equal(elements.journeyProgress.textContent,'2 Formen gesammelt');assert.ok(!html.includes('journeyChapterSelect'),'no chapter dropdown');assert.ok(!html.includes('filterOpen'),'no browsing filters required');assert.ok(elements.journeyNext.disabled);assert.equal((elements.journeyChapters.innerHTML.match(/data-journey=/g)||[]).length,10);assert.ok(elements.journeyChapters.innerHTML.includes('Jetzt spielen'));assert.ok(elements.journeyChapters.innerHTML.includes('Noch entdecken'));
elements.journeyChapters.onclick({target:{closest:()=>({dataset:{journey:'299'}})}});assert.equal(elements.levelNumber.textContent,'02','locked level cannot be opened via handler');elements.chapterTrail.onclick({target:{closest:()=>({dataset:{chapter:'29'}})}});assert.equal(run('journeyChapter'),0,'locked chapter guarded');
elements.journeyContinue.onclick();elements.testAlmost.onclick();assert.equal(run('data.pieces.length-Object.keys(placements).length'),1);elements.testStep.onclick();assert.equal(run('done.has(1)'),true);elements.next.onclick();assert.equal(elements.levelNumber.textContent,'04','normal next skips previously solved puzzle');
run('done=new Set(Array.from({length:9},(_,i)=>i));load(8)');elements.gameJourney.onclick();assert.equal(run('journeyChapter'),0);assert.equal(elements.journeyNext.disabled,true);elements.journeyContinue.onclick();assert.equal(elements.levelNumber.textContent,'10');elements.testFull.onclick();elements.next.onclick();assert.equal(elements.levelNumber.textContent,'11');elements.gameJourney.onclick();assert.equal(run('journeyChapter'),1,'next chapter opens after ten completions');elements.journeyPrevious.onclick();assert.equal(run('journeyChapter'),0);elements.journeyNext.onclick();assert.equal(run('journeyChapter'),1);assert.equal(elements.journeyNext.disabled,true);
// Previously completed and started levels stay accessible, even beyond an earlier gap.
run('done=new Set([0,50]);load(60)');elements.testAlmost.onclick();elements.gameJourney.onclick();assert.ok(elements.chapterTrail.innerHTML.includes('data-chapter="5"'));assert.ok(elements.chapterTrail.innerHTML.includes('data-chapter="6"'),'existing progress chapters remain visible');assert.equal(run('accessible(50)'),true);assert.equal(run('accessible(60)'),true);assert.equal(run('accessible(61)'),false);elements.chapterTrail.onclick({target:{closest:()=>({dataset:{chapter:'6'}})}});assert.equal(run('journeyChapter'),6);elements.journeyChapters.onclick({target:{closest:()=>({dataset:{journey:'60'}})}});assert.equal(elements.levelNumber.textContent,'61');const partial=run('JSON.stringify(placements)');run("routeView('home')");elements.homeContinue.onclick();assert.equal(elements.levelNumber.textContent,'02','main action always guides earliest unfinished');run('load(60)');assert.equal(run('JSON.stringify(placements)'),partial,'older started puzzle is retained');
elements.collection.onclick();assert.equal((elements.galleryGrid.innerHTML.match(/data-motif=/g)||[]).length,run('done.size'),'collection only shows earned forms');assert.ok(elements.galleryGrid.innerHTML.includes('data-motif="50"'));assert.equal(elements.galleryNext.disabled,true);
for(const route of ['menu','gallery','journey','home']){run('routeView('+JSON.stringify(route)+')');assert.equal(Object.values(elements).filter(e=>e.open).length,1);assert.equal(elements[route].open,true);}
run("routeView('menu')");elements.openHelp.onclick();ctx.window.LumaBack();assert.equal(elements.menu.open,true);elements.openBackup.onclick();assert.ok(elements.backupCode.value.includes('"app": "luma-hex"'));const backup=elements.backupCode.value;elements.backupCode.value='broken';elements.checkBackup.onclick();assert.equal(elements.confirmRestore.hidden,true);elements.backupCode.value=backup;elements.checkBackup.onclick();assert.equal(elements.confirmRestore.hidden,false);let reloaded=false;ctx.location.reload=()=>reloaded=true;elements.confirmRestore.onclick();assert.equal(reloaded,true);ctx.window.LumaBack();assert.equal(elements.menu.open,true);ctx.window.LumaBack();assert.equal(elements.home.open,true);assert.equal(ctx.window.LumaBack(),false);
run('closeDialogs();load(60)');const before=run('JSON.stringify(placements)');elements.reset.onclick();assert.equal(elements.resetDialog.open,true);elements.cancelReset.onclick();assert.equal(run('JSON.stringify(placements)'),before);elements.reset.onclick();elements.confirmReset.onclick();assert.equal(run('Object.keys(placements).length'),0);elements.undo.onclick();assert.equal(run('JSON.stringify(placements)'),before);
run("routeView('menu')");elements.jumpNumber.value=300;elements.jumpLevel.onclick();assert.equal(elements.levelNumber.textContent,'300','development jump remains available');run('done=new Set(Array.from({length:TOTAL},(_,i)=>i))');elements.testFull.onclick();elements.next.onclick();assert.equal(elements.journey.open,true);elements.replay.onclick();assert.equal(run('Object.keys(placements).length'),0);
console.log('PASS: guided progression, locked levels/chapters, chapter unlock, previous progress, test bypass, resume, migration, backup, reset, contextual back and all-complete fallback (simulated DOM).');
