const fs=require('fs'),vm=require('vm'),assert=require('assert/strict');
const html=fs.readFileSync(__dirname+'/index.html','utf8'),elements={};
function element(){const classes=new Set();return {setAttribute(k,v){this[k]=v;},style:{},checked:false,classList:{add:n=>classes.add(n),remove:n=>classes.delete(n),toggle:(n,on)=>on?classes.add(n):classes.delete(n)},addEventListener(){},showModal(){this.open=true;},close(){this.open=false;},innerHTML:'',textContent:''};}
for(const m of html.matchAll(/id="([^"]+)"/g))elements[m[1]]=element();
const brand=element(),store=new Map([['lumahex-journey-v4',JSON.stringify({done:[0,2],index:3,introSeen:true,sound:false,attempts:{3:{placements:{0:[0,0]}}}})]]);
const ctx={HexAchievements:require('./achievements.js'),HexCurriculum:require('./curriculum.js'),HexFinish:require('./finish.js'),HexSave:require('./save.js'),HexEngine:require('./engine.js'),HexMotifs:require('./motifs.js'),localStorage:{getItem:k=>store.get(k)||null,setItem:(k,v)=>store.set(k,v)},document:{addEventListener(){},getElementById:id=>{assert.ok(elements[id],'known DOM element '+id);return elements[id];},querySelector:s=>s==='.brand'?brand:null,querySelectorAll:()=>Object.values(elements).filter(e=>e.open)},window:{},navigator:{},location:{protocol:'file:'},setTimeout:()=>1,clearTimeout(){}};
vm.createContext(ctx);const run=s=>vm.runInContext(s,ctx);run(fs.readFileSync(__dirname+'/game.js','utf8'));

assert.equal(elements.levelNumber.textContent,'01','new journey follows curriculum rather than catalog ID');assert.deepEqual(JSON.parse(store.get('lumahex-journey-v5')).done,[0,2],'old collection survives reordered journey');assert.equal(elements.home.open,true);elements.homeContinue.onclick();
elements.gameJourney.onclick();assert.ok(!html.includes('journeyChapterSelect'));assert.equal(elements.journeyNext.disabled,false,'old completed chapters remain reachable');assert.equal((elements.journeyChapters.innerHTML.match(/data-journey=/g)||[]).length,10);assert.ok(elements.journeyChapters.innerHTML.includes('current'));assert.equal(run('tutorialProgress'),6,'existing players are not forced through introduction');
const C=ctx.HexCurriculum,order=C.order;
elements.journeyChapters.onclick({target:{closest:()=>({dataset:{journey:String(order[299])}})}});assert.equal(elements.levelNumber.textContent,'01','locked target cannot be opened');
elements.journeyContinue.onclick();elements.testAlmost.onclick();assert.equal(run('data.pieces.length-Object.keys(placements).length'),1);elements.testStep.onclick();assert.equal(run('done.has(ORDER[0])'),true);elements.next.onclick();assert.equal(elements.levelNumber.textContent,'02');
run('attempts={};done=new Set(ORDER.slice(0,9));load(ORDER[8])');elements.gameJourney.onclick();assert.equal(elements.journeyNext.disabled,true);elements.journeyContinue.onclick();assert.equal(elements.levelNumber.textContent,'10');elements.testFull.onclick();elements.next.onclick();assert.equal(elements.levelNumber.textContent,'11');elements.gameJourney.onclick();assert.equal(run('journeyChapter'),1);elements.journeyPrevious.onclick();assert.equal(run('journeyChapter'),0);elements.journeyNext.onclick();assert.equal(run('journeyChapter'),1);
run('attempts={};done=new Set([0,50]);load(60)');elements.testAlmost.onclick();const partial=run('JSON.stringify(placements)');elements.gameJourney.onclick();assert.equal(run('accessible(50)'),true);assert.equal(run('accessible(60)'),true);assert.equal(run('chapterAccessible(chapterOf(60))'),true);
run('load(60)');assert.equal(run('JSON.stringify(placements)'),partial);elements.collection.onclick();assert.equal((elements.galleryGrid.innerHTML.match(/data-motif=/g)||[]).length,run('done.size'));
for(const route of ['menu','gallery','journey','home']){run('routeView('+JSON.stringify(route)+')');assert.equal(Object.values(elements).filter(e=>e.open).length,1);}
run("routeView('menu')");elements.openHelp.onclick();ctx.window.LumaBack();assert.equal(elements.menu.open,true);elements.openBackup.onclick();const backup=elements.backupCode.value;elements.backupCode.value='broken';elements.checkBackup.onclick();assert.equal(elements.confirmRestore.hidden,true);elements.backupCode.value=backup;elements.checkBackup.onclick();assert.equal(elements.confirmRestore.hidden,false);let reloaded=false;ctx.location.reload=()=>reloaded=true;elements.confirmRestore.onclick();assert.equal(reloaded,true);ctx.window.LumaBack();assert.equal(elements.menu.open,true);ctx.window.LumaBack();assert.equal(elements.home.open,true);assert.equal(ctx.window.LumaBack(),false);
run('closeDialogs();load(60)');const before=run('JSON.stringify(placements)');elements.reset.onclick();assert.equal(elements.resetDialog.open,true);elements.cancelReset.onclick();assert.equal(run('JSON.stringify(placements)'),before);elements.reset.onclick();elements.confirmReset.onclick();assert.equal(run('Object.keys(placements).length'),0);elements.undo.onclick();assert.equal(run('JSON.stringify(placements)'),before);
run("routeView('menu')");elements.jumpNumber.value=1200;elements.jumpLevel.onclick();assert.equal(elements.levelNumber.textContent,'1200');run('done=new Set(ORDER)');elements.testFull.onclick();elements.next.onclick();assert.equal(elements.journey.open,true);elements.replay.onclick();assert.equal(run('Object.keys(placements).length'),0);
console.log('PASS: curriculum navigation, locked chapters, legacy IDs/partial progress, backup, reset, Android back, test jumps and completed journey.');
// Brand-new player: six separate lessons, persisted progress, repeat and skip.
for(const e of Object.values(elements))e.close();store.clear();const fresh={...ctx,window:{}};vm.createContext(fresh);const learn=s=>vm.runInContext(s,fresh);learn(fs.readFileSync(__dirname+'/game.js','utf8'));assert.equal(elements.intro.open,true);elements.start.onclick();assert.equal(learn('tutorialIndex'),0);assert.equal(learn('data.pieces.length'),1);elements.collection.onclick();elements.galleryContinue.onclick();assert.equal(learn('tutorialIndex'),0,'return to unfinished practice does not skip a lesson');const savedAttempts=JSON.stringify(JSON.parse(store.get('lumahex-journey-v5')).attempts);
for(let n=0;n<6;n++){assert.equal(learn('tutorialIndex'),n);assert.equal(elements.lessonGuide.hidden,false);elements.testFull.onclick();assert.equal(learn('tutorialProgress'),n+1);assert.equal(learn('done.size'),0,'lesson does not unlock collection');assert.equal(JSON.stringify(JSON.parse(store.get('lumahex-journey-v5')).attempts),savedAttempts,'lesson does not replace regular pieces');elements.next.onclick();}
assert.equal(elements.home.open,true);assert.equal(learn('tutorialIndex'),null);assert.equal(JSON.parse(store.get('lumahex-journey-v5')).tutorialProgress,6);elements.homeContinue.onclick();assert.equal(elements.lessonGuide.hidden,true);assert.equal(elements.levelNumber.textContent,'01');
elements.gameJourney.onclick();elements.openCourse.onclick();assert.equal(learn('tutorialIndex'),0,'completed course can be replayed');elements.gameHome.onclick();assert.equal(learn('tutorialIndex'),null,'home exits practice safely');elements.homeContinue.onclick();assert.equal(elements.lessonGuide.hidden,true);elements.openCourse.onclick();elements.skipLesson.onclick();assert.equal(learn('tutorialIndex'),null);
learn('tutorialProgress=2;persist()');for(const e of Object.values(elements))e.close();const resumed={...ctx,window:{}};vm.createContext(resumed);vm.runInContext(fs.readFileSync(__dirname+'/game.js','utf8'),resumed);elements.homeContinue.onclick();assert.equal(vm.runInContext('tutorialIndex',resumed),2,'unfinished course resumes at next lesson');
console.log('PASS: six playable lessons, course resume/replay/skip, introduction migration and isolation from regular progress.');

// Only adjacent solved stations light their connecting path, without repeated visible labels.
run('attempts={};done=new Set(ORDER.slice(0,2))');let pathHTML=run('pathMarkup(ORDER.slice(0,10))');assert.equal((pathHTML.match(/class="completed-route"/g)||[]).length,1);assert.equal((pathHTML.match(/<text /g)||[]).length,10);assert.ok(!/<(?:b|span|small)>/.test(pathHTML),'station labels appear only inside hexagons');run('done=new Set([ORDER[0],ORDER[2]])');assert.equal((run('pathMarkup(ORDER.slice(0,10))').match(/class="completed-route"/g)||[]).length,0,'unfinished gap does not light up');run('done=new Set(ORDER.slice(0,10))');assert.equal((run('pathMarkup(ORDER.slice(0,10))').match(/class="completed-route"/g)||[]).length,9);console.log('PASS: completed path segments, unfinished gaps and one visible number per station.');
run('tutorialIndex=null;done=new Set();load(ORDER[0]);testAction("full")');
assert.equal(elements.winTitle.textContent,'Geschafft!');assert.ok(elements.winQuote.textContent.length>10);assert.equal(elements.winText.textContent,'');
const firstText=elements.winQuote.textContent;run('complete(false)');assert.equal(elements.winQuote.textContent,firstText);
run('done=new Set(ORDER.slice(0,9));load(ORDER[9]);testAction("full")');assert.equal(elements.winTitle.textContent,'Etappe geschafft!');assert.equal(elements.winEyebrow.textContent,'TESTLAUF');assert.ok(elements.winText.textContent.includes('zehn'));assert.ok(JSON.parse(store.get('lumahex-journey-v5')).finishMemory);
console.log('PASS: normal completion, stable text, milestone completion and persisted text history.');
const F=ctx.HexFinish;
for(const kind of ['fact','quote','riddle']){const l=F.active.find(x=>x.kind===kind);run('runMoment=HexFinish.get('+JSON.stringify(l.id)+');completionAwarded=true;complete(false)');assert.equal(elements.winQuote.textContent,l.text);if(kind==='riddle'){assert.ok(elements.winExtra.innerHTML.includes('<details'));assert.ok(elements.winExtra.innerHTML.includes('Antwort ansehen'));assert.ok(!elements.winExtra.innerHTML.includes('<details open'));}if(kind==='quote')assert.ok(elements.winExtra.innerHTML.includes(l.author));if(kind==='fact')assert.ok(elements.winExtra.innerHTML.includes(l.source.url));}
run('loadLesson(0);testAction("full")');assert.equal(elements.winExtra.innerHTML,'');
console.log('PASS: fact source, quote attribution, optional riddle answer and lesson isolation.');


run('load(ORDER[0],true);placements=E.autoPlace(data,placements,"full").placements;testUsed=false;complete(false)');const earned=run('finishMemory.byPuzzle[index]'),readCount=run('finishMemory.seen.length');assert.ok(earned);run('complete(false);showDetail(index);load(index)');assert.equal(run('finishMemory.seen.length'),readCount,'view/reload/repeated callback never awards');run('load(index,true);placements=E.autoPlace(data,placements,"full").placements;testUsed=false;complete(false)');assert.notEqual(run('finishMemory.byPuzzle[index]'),earned);assert.equal(run('finishMemory.history[index].length'),2,'replay retains both readings');const afterReplay=run('finishMemory.seen.length');run('load(ORDER[1],true);testAction("full")');assert.equal(run('finishMemory.seen.length'),afterReplay,'test completion does not consume personal pool');
console.log('PASS: real completion/replay awards once, archive retains history, viewing/reload/test modes consume nothing.');

for(const kind of ['fact','quote','humor','thought','riddle']){const l=F.active.find(x=>x.kind===kind);const extra=run('momentExtra(HexFinish.get('+JSON.stringify(l.id)+'))');assert(!extra.includes('moment-kind'));if(l.source){assert(extra.includes('href="'+l.source.url+'"'));assert(!extra.includes('target="_blank"'));}}
console.log('PASS: no category captions, source links navigate without unsupported new windows.');

run('done=new Set();for(const n of Object.keys(records))delete records[n];finishMemory.seen=[];finishMemory.recent=[];finishMemory.history={};finishMemory.byPuzzle={};load(ORDER[0],true);placements=E.autoPlace(data,placements,"full").placements;testUsed=false;complete(false)');assert(elements.winAchievements.innerHTML.includes('Rätselreise'));run('showAchievements()');assert(elements.achievements.open);assert(elements.achievementList.innerHTML.includes('role="progressbar"'));assert(elements.achievementCount.textContent.includes('3 von 48'));run('backView()');assert(!elements.achievements.open);assert(elements.gallery.open);run('load(ORDER[1],true);testAction("full")');assert.equal(elements.winAchievements.innerHTML,'');assert.equal(run('achievementState().find(a=>a.id==="journey-10").value'),1);run('loadLesson(0);testAction("full")');assert.equal(elements.winAchievements.innerHTML,'');
console.log('PASS: achievement unlock shown on genuine completion, accessible list/back navigation, test and lesson exclusion.');

assert(!html.includes('openMoments'));assert(!html.includes('momentPager'));run('showDetail(index)');assert.equal(elements.detailQuotes.innerHTML,'');assert(!F.active.some(l=>elements.detailQuotes.innerHTML.includes(l.text)));console.log('PASS: no reading archive or text collection entry; completion texts retained.');

run('done=new Set(ORDER.slice(0,100));for(const n of done)records[n]={mode:"own",hints:0};showAchievements()');assert(elements.achievementHero.innerHTML.includes('data-skin="glass"'));run('chooseSkin("glass")');assert.equal(run('selectedSkin'),'glass');assert.equal(JSON.parse(store.get('lumahex-journey-v5')).skin,'glass');run('chooseSkin("rings")');assert.equal(run('selectedSkin'),'glass','locked reward cannot be equipped');run('selectedSkin="rings";render()');assert(elements.board.innerHTML.includes('stroke-width="5"'));run('selectedSkin="pearl";render()');assert(elements.board.innerHTML.includes('radialGradient id="pearl'));assert(!elements.achievementList.innerHTML.includes('Lesemoment'));console.log('PASS: skin rewards, equip/persist, locked-set protection, ring and pearl rendering.');

run('done=new Set();for(const n of Object.keys(records))delete records[n];selectedSkin="classic";showAchievements()');assert.equal((elements.achievementHero.innerHTML.match(/data-skin=/g)||[]).length,12);const beforeTest=run('JSON.stringify({done:[...done],records,finishMemory})');run('setSkinTest(true);showAchievements()');assert(!elements.achievementHero.innerHTML.includes('disabled'));for(const set of ctx.HexAchievements.skins){run('chooseSkin('+JSON.stringify(set.id)+')');assert.equal(run('selectedSkin'),set.id);assert(!elements.tray.innerHTML.includes('NaN'));assert(!elements.board.innerHTML.includes('undefined'));}assert.equal(run('JSON.stringify({done:[...done],records,finishMemory})'),beforeTest);assert.equal(JSON.parse(store.get('lumahex-skin-preview-v1')).enabled,true);assert(elements.achievementHero.innerHTML.includes('Testmodus'));assert(run('defs()').includes('id="chrome"'));run('setSkinTest(false)');assert.equal(run('selectedSkin'),'classic');run('chooseSkin("chrome")');assert.equal(run('selectedSkin'),'classic');run('setSkinTest(true);chooseSkin("enamel")');const reload={...ctx,window:{}};vm.createContext(reload);vm.runInContext(fs.readFileSync(__dirname+'/game.js','utf8'),reload);assert.equal(vm.runInContext('skinTest',reload),true);assert.equal(vm.runInContext('selectedSkin',reload),'enamel');console.log('PASS: twelve sets render/select, tester unlock persists across reload, no achievements granted, normal gates restored on exit.');

const currentContext=reload;const check=s=>vm.runInContext(s,currentContext);check('load(ORDER[0],true);done=new Set(ORDER.slice(0,2))');let station;for(const set of ctx.HexAchievements.skins){check('selectedSkin='+JSON.stringify(set.id));const markup=check('pathMarkup(ORDER.slice(0,10))');if(station)assert.equal(markup,station,'journey independent of selected stones');station=markup;}check('closeDialogs();$("win").showModal();$("winJourney").onclick()');assert(!elements.win.open);assert(elements.journey.open);assert.equal(Object.values(elements).filter(e=>e.open).length,1);assert(fs.readFileSync(__dirname+'/style.css','utf8').includes('reveal 1.6s'));assert(fs.readFileSync(__dirname+'/game.js','utf8').includes('},1700);'));console.log('PASS: readable consistent journey stations across all twelve sets, direct finish-to-journey and longer reveal.');

check('done=new Set(ORDER.slice(0,20));showJourney();$("openChapterPicker").onclick()');assert(elements.chapterPicker.open);assert(!elements.journey.open);check('$("chapterTrail").onclick({target:{closest:()=>({dataset:{chapter:"0"}})}})');assert(elements.journey.open);assert(!elements.chapterPicker.open);assert.equal(check('journeyChapter'),0);check('$("openChapterPicker").onclick();backView()');assert(elements.journey.open);assert(!elements.chapterPicker.open);assert.equal(Object.values(elements).filter(e=>e.open).length,1);const section=html.slice(html.indexOf('<dialog id="journey"'),html.indexOf('</dialog>',html.indexOf('<dialog id="journey"')));assert(!section.includes('class="primary"'));assert(!section.includes('class="course-link"'));assert(!section.includes('id="chapterTrail"'));assert(section.includes('id="openChapterPicker"'));console.log('PASS: compact journey head, optional chapter overview, chapter selection/back and one active screen.');
